[[redirects]]
  from = "/favicon.ico"
  to = "https://gfork.dahi.icu/favicon.ico"
  status = 301
  force = true

[[redirects]]
  from = "/scripts/*"
  to = "https://static-sg-apse1-primary-mirror-aws-s3-cloudfront-public-cdn.dahi.edu.eu.org/scripts/:splat"
  status = 308

[[redirects]]
  from = "/*"
  to = "https://dahisea.github.io/GF-WWW/"
  status = 200
