[[redirects]]
  from = "/favicon.ico"
  to = "https://gfork.dahi.icu/favicon.ico"
  status = 301
  force = true

[[redirects]]
  from = "/scripts/*"
  to = "https://cdn-1-mod-ugf.zh-cn.eu.org/scripts/:splat"
  status = 308

[[redirects]]
  from = "/*"
  to = "https://gfork.dahi.icu/404"
  status = 301
